### ISSUE TITLE
Error appears when saving a location remote/ cloud connected on Android app

### ISSUE THREAD

**Issue by danieltaivan** [sprinkler/rainmachine-android-app#1]
STEPS:
1. Enter Android Sprinkler app
2. Select from Network Settings> Local Discovery 
3. Navigate to System> System Settings> Location
4. Tap/ enter into Location menu 
5. Click Change Location and enter another address
6. Click Save button

EXPECTED RESULT:
Location should be changed to new location successfully.

ACTUAL RESULT:
Error appears when saving a location on Android app and new location is not saved.

**Comment by danieltaivan** [comment]
![error_location_android](https://cloud.githubusercontent.com/assets/16254241/12049573/607538d8-aef1-11e5-8311-d747cdc73984.jpg)

**Comment by kaciula** [comment]
@danieltaivan Thanks for posting the issue. For now on, please post the issues on the internal github repository for the Android app:

https://github.com/sprinkler/android-app

If you do not have access, please ask Bogdan to give you the necessary access permissions.

**Comment by kaciula** [comment]
The issue seems to be related to the cloud API and is not directly connected to the mobile app. I will let the cloud team know about it.
