### ISSUE TITLE
Accessibility: provide content descriptions for UI controls

### ISSUE THREAD

**Issue by vick08** [sprinkler/rainmachine-android-app#2]
The current version of the RainMachine app in the Play Store is missing content descriptions on multiple UI elements, e.g. tab names, and controls next to each zone, to name a few. Without content descriptions the meaning of those controls is not known to blind users who rely on Talkback screen reader to interface with Android. See more information on [Android Accessibility for Developers](http://g.co/androidaccessibility) website.
To quickly scan your app for these and other accessibility errors, feel free to use [Accessibility Scaner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en) from Google.

**Comment by kaciula** [comment]
@vick08 Thanks for the feedback. We are aware that the app needs improvements with regard to accessibility support. Are you or someone you know trying to use the app with Talkback?

**Comment by vick08** [comment]
Yes. This is exactly why I filed a bug. As it stands now, I have to memorize my steps very carefully when using the app -- not a very efficient experience.
Thanks for acknowledging the issue and let me know if I can help in any way.

**Comment by vick08** [comment]
Happy New year! Any update on the issue?

**Comment by vick08** [comment]
@kaciula any news on the possible fix?

**Comment by kaciula** [comment]
@vick08 Hi Victor. Let me know what are your main use cases when using the app that you would like to be made more accessible.

**Comment by vick08** [comment]
Thanks for the response @kaciula 
It would be great to solve the issue with content descriptions first. They are at least the most important for my particular use case. Some of the examples include:
1. Tabs at the top of the screen
2. Play/Stop buttons for every zone (and anyother related actions).
Thanks again!

**Comment by kaciula** [comment]
@vick08 I've made an update to our beta channel with some quick accessibility improvements to tabs, zones and programs screens. The version is 4.5.9. Let me know if it's ok and what other specific improvements you would like.

In order to download this version, you need to become a beta tester for the app. Please register here: https://play.google.com/apps/testing/com.rainmachine

**Comment by vick08** [comment]
@kaciula thanks so much for the fixes. They are super helpful! Really appreciate them!

**Comment by vick08** [comment]
@kaciula once again, thanks a lot for the improvements!
Please feel free to close this bug once the app has been released to the play store.
